accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    url('register/', views.register_view, name="register"),
    url('profile/', views.profile_view, name="profile"),
    url('login/', views.login_view, name="login"),
    url('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    url('password-reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'), name='password_reset'),
    url('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    url('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    url('password-reset-complete', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
]

donations/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'donations'

urlpatterns = [

    url(r'^$', views.donation_create, name="donations"),
    url(r'^(?P<donation_id>\d+)/$', views.add_items, name="items"),
    url(r'^search/$', views.search, name='search'),
    #url('donations_list', views.donations_list, name="donations_list"),
    #url('items/', views.add_items, name="items"),

]

events/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [

    url(r'^$', views.create_event, name='create_event'),
    url(r'volunteer/^$', views.volunteer, name='volunteer'),
    url(r'^(?P<event_id>\d+)/$', views.add_positions, name='positions'),
    url(r'^event_positions/$', views.event_positions, name='event_positions'),
]

hap_pea_foods/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from . import views


#styling changes to ADMIN site
admin.site.site_header = 'HAP-PEA FOODS' # changes blue banner
admin.site.index_title = 'ADMIN DASHBOARD' # changes title under blue banner
admin.site.site_title = 'Hap-Pea Foods Admin' # changes browser tab title

urlpatterns = [
    path('admin/', admin.site.urls),
    url('about/', views.about, name="about"),
    url('donate/', include('donations.urls')),
    url('survey/', include('survey.urls')),
    url('find_help/', views.find_help, name="find_help"),
    url('partners/', views.partners, name="partners"),
    url('accounts/', include('accounts.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url('stories/', include('stories.urls')),
    url('events/', include('events.urls')),
    url('volunteer/', views.volunteer, name="volunteer"),
    url('portal/', views.portal, name="portal"),
    url('contact/', views.contact, name="contact"),
    url('createevent/', views.createevent, name="createevent"),
    url('moneydonations/', views.moneydonations, name="moneydonations"),
    url('organizations/', views.organizations, name="organizations"),
    url('mycalendar/', views.mycalendar, name="mycalendar"),
    url('non_disc_stmt/', views.non_disc_stmt, name="non_disc_stmt"),
    url('privacy/', views.privacy, name="privacy"),
    url('facts/', views.facts, name="facts"),
    url('terms_cond/', views.terms_cond, name="terms_cond"),
    #path('', include('qr_code.urls', namespace='qr_code')),
    url('', views.homepage, name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stories/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'stories'

urlpatterns = [

    url(r'^$', views.stories_list, name="stories"),
    url('create_story/', views.story_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', views.story_detail, name="detail"),
]

templates/about.html
{% extends 'base_layout.html' %}
{% block title %} Hap-Pea Foods | About Us {% endblock %}
{% block content %}

  <div class="about-page">
    <h1>About Us</h1>

    <p>The problem we are facing is food insecurities caused by food waste and shortage through a lack of communication. Every day people go hungry because they cannot provide food for their families. This is the concept of food insecurities. Food waste and shortage exacerbate this situation. Food waste is the overabundance of food were unused, sold, or eaten food is thrown out while food shortage is when food is in high demand. The US has in place programs to help families suffering from food insecurities. However, these programs are not always successful because they lack the communication needed for programs to talk to one another. Too often a program may have too much food where another has too little. Hence food waste and shortage. The concept of Hap-Pea Foods is to have these programs communicate with each other reducing food insecurities in the process. </p>

    <p>Food banks, food charities, help people in need regarding food needs. They provide food to those who cannot otherwise provide because of financial means. A household that doesn’t make enough money may lack the ability to put food on the table and thus goes to a food bank or charity to get food that is donated by people or companies. When a food bank doesn’t have enough food, they need a place to search for available food. Hap-Pea food provides a website to make this connection. When food banks have too much food, instead of throwing away the food, they can use the Hap-Peas food website to find banks and charities that require what they have. Hap-Pea foods also provide a connection for people who want to volunteer their services to these banks and charities since most of them rely on volunteers for their labor and workforce. </p>

    <p>Hap-Pea foods will be a website with a centralized database containing companies, charities, and banks that have food or need food. Companies, charities, and banks can search the database for what they need and search for how to help others with what they have. It provides a place where volunteers can join the workforce and offer their services to others who are in need. </p>


  </div>
{% endblock %}

templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="google-site-verification" content="IUpq5v_b5xf3uMM3y1vAXFEgzreyeoDetMuNzTU5InU" />
    <!-- bootstrap 4.0 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Style CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Icon for page tab -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <!-- font awesome stylesheet  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://happeafoodsmedia.s3-us-west-1.amazonaws.com/static/happeamap.js"></script>

    <title>{% block title %}home{% endblock %}</title>
  </head>
  <body>
    <header>
     <div class="head-container">
       <div class="sm">
         <!-- Register login Portal logout Links -->
         {% if user.is_authenticated %}
           <h5>Welcome {{user.username}}</h5>
           <i class="far fa-user" style="color: black"></i>
           <a href="{% url 'portal' %}">My Portal</a>
           <a href="{% url 'accounts:logout' %}">Logout</a>
         {% else %}
           <i class="far fa-user" style="color: black"></i>
           <a href="{% url 'accounts:register' %}">Register</a>
           <a href="{% url 'accounts:login' %}">Login</a>
        {% endif %}

          <!-- Social Media Links -->
         <i class="fab fa-facebook-f" style="color: blue"></i>
         <i class="fab fa-twitter" style="color: lightblue"></i>
         <i class="fab fa-google-plus" style="color: green"></i>
         <i class="fab fa-instagram" style="color: grey"></i>
         <i class="fab fa-youtube" style="color: red"></i>
       </div>
     </div>
    </header>
    <!-- Start NavBar -->
    <nav class="navbar navbar-expand-md navbar-custom justify-content-evenly">
      <a href="/" class="navbar-brand"><img src="{% static 'logo2.jpg' %}" class = navimage alt=""></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCustom">
        <i class="fa fa-bars fa-lg py-1 text-white"></i>
      </button>
      <div class="navbar-collapse collapse justify-content-center align-items-center w-100" id="navbarCustom">
        <ul class="navbar-nav mx-auto text-center">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle px-3" href="#" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  About
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'about' %}">About Us</a>
                    <a class="dropdown-item" href="{% url 'partners' %}">Partners</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle px-3" href="#" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Donate
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'donations:search' %}">Search Donations</a>
                    <a class="dropdown-item" href="{% url 'donations:donations' %}">Donate Food</a>
                    <a class="dropdown-item" href="{% url 'volunteer' %}">Volunteer</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link px-3" href="{% url 'find_help' %}">Find Help</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle px-3" href="#" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Events
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'events:create_event' %}">Create an Event</a>
                    <a class="dropdown-item" href="{% url 'events:event_positions' %}">Volunteer for an Event</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle px-3" href="#" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Survey
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'list' %}">Survey Questions</a>
                    <a class="dropdown-item" href="{% url 'qrCode' %}">Survey QR Code</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle px-3" href="#" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Facts and Media
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Hunger in the US</a>
                    <a class="dropdown-item" href="{% url 'stories:stories' %}">Stories</a>
                    <a class="dropdown-item" href="{% url 'facts' %}">Media</a>
                </div>
            </li>

        </ul>
        <!-- Search Google Form -->
        <form class="form-inline">
           <script async src="https://cse.google.com/cse.js?cx=3555679745fbd16c3"></script>
           <div class="gcse-search"></div>
        </form>
    </div>
</nav>
    <!-- Start Wrapper -->
    <div class="wrapper_container">
      <!-- messages -->
      {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} text-center">
          {{ message }}
        </div>
        {% endfor %}
      {% endif %}

      <!-- begin content for wrapper -->
      {% block content %}

      {% endblock %}
    </div>
    <!-- End wrapper -->

    <!-- FOOTER -->
    <footer>
      <div class="foot-container">

        <div class="foot-columns">
          <div class="about"> <!-- flex box 1 -->
            <div class="statement">
              <img src="{% static 'logo2.jpg' %}" class="img-logo" alt="peas">
              <p> Hap Pea Foods is dedicated to ending food insecurity. We work tiredlessly with companies around the states to make sure there is enough food on the table for every household.  We do right by people and the planet. Together, we drive meaningful change in communities around the world.</p>
            </div>
            <div class="sm">
              <i class="fab fa-facebook-f" style="color: blue"></i>
              <i class="fab fa-twitter" style="color: lightblue"></i>
              <i class="fab fa-google-plus" style="color: green"></i>
              <i class="fab fa-instagram" style="color: grey"></i>
              <i class="fab fa-youtube" style="color: red"></i>
            </div>
          </div>

          <div class="foot-links"> <!-- flex box 2 -->
            <ul>
              <li><a href="{% url 'home' %}">Home</a></li>
              <li><a href="{% url 'about' %}">About</a></li>
              <li><a href="{% url 'partners' %}">Partners</a></li>
              <li><a href="{% url 'stories:stories' %}">Stories</a></li>
              <li><a href="{% url 'facts' %}">Facts and Media</a></li>
              <li><a href="{% url 'find_help' %}">Find Help</a></li>
            </ul>
          </div>
          <div class="foot-links-2"><!-- flex box 3 -->
            <ul>
              <li><a href="{% url 'portal' %}">My Portal</a></li>
              <li><a href="{% url 'list' %}">Survey Questions</a></li>
              <li><a href="{% url 'volunteer' %}">Volunteer</a></li>
              <li><a href="{% url 'events:create_event' %}">Create an Event</a></li>
              <li><a href="{% url 'donations:donations' %}">Donate</a></li>
              <li><a href="{% url 'donations:search' %}">Search Donations</a></li>
              <li><a href="{% url 'organizations' %}">Organizations</a></li>

            </ul>
          </div>

          <div class="subscribe"> <!-- flex box 4 -->
            <form action="/action_page.php">
              <input type="email" placeholder="Email..." name="email">
              <button type="submit">Subscribe</button>
            </form>
          </div>

          <div class="contact"><!-- flex box 5 -->
            <h2><a href="{% url 'contact' %}">Contact Us</a></h2>
            <ul>
              <li><i class="fa fa-map-marked-alt" style="color: black"></i><a href="https://maps.google.com">Google Maps</a></li>
              <li><i class="fa fa-city" style="color: black"></i>1234 A Random Street, City, State, 00000</li>
              <li><i class="fa fa-phone" style="color: black"></i>(987) 654-3210</li>
              <li><i class="fa fa-envelope" style="color: black"></i> test@test.com</li>
          </ul>
          </div>
        </div>

        <div class="foot-columns">
          <div class="copyright">
            <p>Copyright &copy; 2021 Website Created by David Boss, Suzanne Kaufman, and Mallory Dodds. All Rights Reserved.
              <br />
              <a href="{% url 'terms_cond' %}">Terms and Conditions</a> | <a href="{% url 'privacy' %}">Privacy Policy</a> | <a href="{% url 'non_disc_stmt' %}">Non Discrimination Statement</a></p>
          </div>
        </div>

      </div>
    </footer>

    <!-- /* scripts for slider */ -->
    <script type="text/javascript">
      var counter = 1;
      setInterval(function(){
        document.getElementById('radio' + counter).checked = true;
        counter++;
        if(counter >4){
          counter = 1;
        }
      }, 5000);
    </script>

  </body>
</html>

templates/contact.html
{% extends 'base_layout.html' %}
{% block title %} Hap-Pea Foods | Contact Us {% endblock %}
{% block content %}
  <div class="c-information">
    <h1>Contact Us</h1>
    <h2><i class="fas fa-building"></i>Address</h2>
    <p>1234 Any Street</p>
    <p>Tempe, Arizona, 85283</p>
    <br/>
    <h2><i class="fas fa-phone-alt"></i>Phone</h2>
    <p>(987) 654-3210</p>
    <br/>
    <h2><i class="fas fa-at"></i>Email</h2>
    <p>happeafoods@asu.com</p>
  </div>

  <div class="c-form-head">
    <hr><i class="far fa-envelope"></i><hr>
  </div>

  <div class="contact_form">
    <h3>Please fill out the following form. We will contact you within 24 hours.</h3>

    <form action="action_page.php">

      <label for="fname">First Name</label>
      <input type="text" id="fname" name="firstname" placeholder="Your name..">

      <label for="lname">Last Name</label>
      <input type="text" id="lname" name="lastname" placeholder="Your last name..">

      <label for="country">Country</label>
      <select id="country" name="country">
        <option value="australia">Australia</option>
        <option value="canada">Canada</option>
        <option value="usa">USA</option>
      </select>

      <label for="number">Telephone Number</label>
      <p><input type="tel" id="telnum" name="number" placeholder="Your Phone Number">

      <p><label for="subject">Subject</label>
      <textarea id="subject" name="subject" placeholder="Write something.." style="height:200px"></textarea>

      <input type="submit" value="Submit">

    </form>
  </div>

{% endblock %}

templates/donate.html
{% extends 'base_layout.html '%}
{% block title %}Hap Pea Foods | Donate{% endblock %}
{% block content %}
<h1><center>Donation Page for Hap-Pea Foods</center></h1><br/>
<p>Welcome to our donation page.</p>
{% endblock %}

templates/googleb992673f1334124f.html
google-site-verification: googleb992673f1334124f.html

templates/homepage.html
{% extends 'base_layout.html' %}
{% block title %} Hap-Pea Foods | Home {% endblock %}
{% block content %}
{% load static %}

  <!-- slider -->

  <div class="slider container"> 
    <figure>
      <img src="{% static 'handout.jpg' %}">
      <img src="{% static 'prepare.jpg' %}">
      <img src="{% static 'receive.jpg' %}">
      <img src="{% static 'giving.jpg' %}">
      <img src="{% static 'handout.jpg' %}">
    </figure>
  </div>

  <!-- left container -->
  <div class="l_containter">
    <div class="column">
      <div class="leftblock">
        <h1>What is a food bank?</h1>

        <p>A food bank is a non-profit organization that collects and distributes food to hunger-relief charities. Food banks act as food storage and distribution depots for smaller front line agencies; and usually do not themselves give out food directly to people struggling with hunger.</p>
        <br/>
        <p>Food banks in the U.S. are very diverse – from small operations serving people spread out across large rural areas to very large facilities that store and distribute many millions of pounds of food each year, and everything in between. A variety of factors impact how food banks work, from the size of the facility to the number of staff members.  But, one thing all food banks have in common is that they rely on donors and volunteers to carry out their day-to-day operations. </p>

        <h1>How does the Hap-Pea Foods network of food banks work?</h1>
        <div class="row1">
          <div class="image-col">
            <img src="{% static '005-food.png' %}" alt="">
          </div>
          <div class="text">
            <h3>Securing food</h3>
            <p>Hap-Pea Foods secures donations from national food and grocery manufacturers, retailers, shippers, packers and growers and from government agencies and other organizations. We have staff that work closely with the partners to match excess food with the food banks that most need it.</p>
          </div>
        </div>

        <div class="row2">
          <div class="image-col">
            <img src="{% static '002-truck.png' %}" alt="">
          </div>
          <div class="text">
            <h3>Shipping and Storage</h3>
            <p>The Hap-Pea Foods network of food banks receive and safely stores donated food and grocery products. Hap-Pea Foods supports member food banks with training, oversight and equipment grants to ensure perishable and non-perishable food is handled and stored properly.</p>
          </div>
        </div>

        <div class="row3">
          <div class="image-col">
            <img src="{% static '001-supply-chain.png' %}" alt="">
          </div>
          <div class="text">
            <h3>Distributing Food</h3>
            <p>The food banks distribute food and grocery items through food pantries and meal programs that serve families, children, seniors and individuals at risk of hunger. Last year alone, the Hap-Pea Foods network distributed more than 3.6 billion meals to people in need.</p>
          </div>
        </div>

        <div class="row4">
          <div class="image-col">
            <img src="{% static '006-support.png' %}" alt="">
          </div>
          <div class="text">
            <h3>Supporting the people we serve</h3>
            <p>The Hap Pea Foods nationwide network of food banks also supports programs that improve food security among the people we serve; educates the public about the problem of hunger; and advocates for legislation that protects people from going hungry. Individuals, charities, businesses and government all have a role in ending hunger.</p>
          </div>
        </div>

      </div> <!-- end leftblock -->

      <div class="home-calendar">
        <h1>Calendar of Events<a href="https://www.timeanddate.com/calendar/"><i class="far fa-calendar-alt" style="color: black"></i></a></h1> <!-- Module insert here for calendar -->

        <div class="events-grid" style="margin-top: 20px; display: grid; grid-template-columns: 300px 300px; grid-gap: 20px;">
          {% for event in event_list %}
            <div class="event" style="border: 3px solid #E32636; padding: 3%;">
              <h2 class="text-center">{{event.eventTitle}}</h2>
              <p>{{event.eventDate}}</p>
              <p> Start: {{event.startTime}} End: {{event.endTime}}</p>
            </div>
          {% endfor %}
        </div>

      </div> <!-- end calendar -->
    </div> <!-- end column -->
  </div> <!-- end l_container -->


{% endblock %}

templates/moneydonations.html
{% extends 'base_layout.html' %}
{% load static %}
{% block title %} Hap-Pea Foods | Donate Money {% endblock %}
{% block content %}
  <div class="wrapper_pay">
    <div class="payment">
      <div class="payment-logo">
        <p>HPF</p>
      </div>
      <h2>Donate Money</h2>

      <div class="payment_form">
        <div class="card space icon-relative">
          <label class="label">Name On Card:</label>
          <input type="text" class="input" name="card_holder" placeholder="Name Here">
          <i class="fas fa-user"></i>
        </div>

        <div class="card space icon-relative">
          <label class="label">Card Number:</label>
          <input type="text" class="input" name="card_number" placeholder="Card Number">
          <i class="far fa-credit-card"></i>
        </div>

        <div class="card-grp space">
          <div class="card-item icon-relative">
            <label class="label">Exp. Date:</label>
            <input type="text" class="input" name="exp_date" placeholder="00/00">
            <i class="far fa-calendar-alt"></i>
          </div>

          <div class="card-item icon-relative">
            <label class="label">CVC:</label>
            <input type="text" class="input" name="cvc" placeholder="000">
            <i class="fas fa-lock"></i>
          </div>
        </div>

        <div class="btn">Pay</div>
      </div>

    </div>
  </div>


{% endblock %}

templates/mycalendar.html
{% extends 'base_layout.html' %}
{% block title %} Hap-Pea Foods | My Calendar {% endblock %}
{% block content %}
  <div class="calendar">
    <h1>My Calendar</h1>
    <a href="https://www.timeanddate.com/calendar/"><i class="far fa-calendar-alt" style="color: black"></i></a>
  </div>
{% endblock %}

templates/organizations.html
{% extends 'base_layout.html' %}
{% block title %} Hap-Pea Foods | Organziations {% endblock %}
{% block content %}
{% load static %}
  <center><h1>Organizations</h1>


  <p> Download this form: </p>
  <a href="{% static 'organizationform.pdf' %}" download>
    <img src="{% static 'form.jpg' %}" width="200px">
  </a>
  </center>



{% endblock %}

templates/partners.html
{% extends 'base_layout.html' %}
{% block title %} Hap-Pea Foods | Partners {% endblock %}
{% block content %}
{% load static %}

<div class="partner-main">
  <h1>Hap-Pea Foods Partners</h1><br/>
  <div class="partners text-center">
    <a href="https://www.feedingamerica.org/"><img src="{% static 'feedingamerica.png' %}"></a>
    <a href="https://www.starbucks.com/"><img src="{% static 'starbucks.png' %}"></a>
    <a href="https://midwestfoodbank.org/home"><img src="{% static 'midwest.png' %}"></a>
    <a href="https://www.firstfoodbank.org/"><img src="{% static 'stmarys.png' %}"></a>
    <a href="https://www.panerabread.com/en-us/home.html"><img src="{% static 'panera.png' %}"></a>
  </div>
</div>
{% endblock %}

templates/volunteer.html
{% extends 'base_layout.html' %}
{% block title %} Hap-Pea Foods | Volunteer {% endblock %}
{% block content %}
{% load static %}



  <div class="v_img_banner" style="margin-top:5%;">
    <h1 class="text-center"><img src="{% static 'colunteer.jpg' %}" style="width:20%; height:20%;"></h1>
  </div>
  <br>
  <div class="v_content">
    <h2>Become a volunteer. Your time and talent can make a real difference in peoples live's. Together we can end hunger and food waste.</h2>
  </div>

  <div class="v_options">
    <h3>6 ways to make a difference</h3>

    <ul class="text-center">
      <li><img src="{% static '003-charity.png' %}" alt=""><br><h4>Volunteer</h4></li>
      <li><img src="{% static '004-canned-food.png' %}" alt=""><br><h4>Start A Food Drive</h4></li>
      <li><img src="{% static '006-building.png' %}" alt=""><br><h4>Neighborhood Check</h4></li><br/>
      <li><img src="{% static '001-megaphone.png' %}" alt=""><br><h4>Advocate</h4></li>
      <li><img src="{% static '005-calendar.png' %}" alt=""><br><h4>Attend an Event</h4></li>
      <li><img src="{% static '002-online-donation.png' %}" alt=""><br><h4>Donate</h4></li>
    </ul>

    <div class="v_links">
      <a href="{% url 'events:event_positions' %}">Volunteer Match</a> |
      <a href="">New Volunteer Applicants</a> |
      <a href="{% url 'donations:donations' %}">Donate Now</a>
    </div>
    <div class="container">
      <h3 class="text-center">Volunteering During the Pandemic</h3>

      <p>During the COVID-19 pandemic, many food banks have experienced personnel shortages because their volunteer bases are comprised largely of individuals over the age of 60, a group that has been identified as more vulnerable to COVID-19. Food banks can prepackage food items and hold drive-thru distributions to help workers, volunteers, and clients adhere to social distancing guidelines and stay safe.</p>

      <p>Volunteers are needed now, around the world, more than ever to provide relief from the destruction that COVID-19 has had on communities. Food banks are seeing a ramp-up in the need for volunteers, due to this unprecedented pandemic. Volunteers are the heart of these organizations and rely on them to help reach goals and drive mission-attainment. In fact, most nonprofits would not be able to achieve goals without the support of volunteers.</p>

      <p>Volunteers have an opportunity to really make a big difference within their communities, right now. The COVID-19 pandemic has impacted food banks and the number of volunteers that they have available for much-needed shifts.</p>

      <p>The current situation, involving COVID-19, is calling for food banks to put protocols in place to protect the health of staff, clients, and volunteers. These protocols include social distancing, health, and wellness awareness strategies, and providing flexible shifts. For volunteers, wanting to aid their time during this crisis, there are a few practical steps they can take to protect their health and reduce risk.</p>
    </div>

  </div>
{% endblock %}