events/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [

    url(r'^$', views.create_event, name='create_event'),
    url(r'volunteer/^$', views.volunteer, name='volunteer'),
    url(r'^(?P<event_id>\d+)/$', views.add_positions, name='positions'),
    url(r'^event_positions/$', views.event_positions, name='event_positions'),
]

hap_pea_foods/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from . import views


#styling changes to ADMIN site
admin.site.site_header = 'HAP-PEA FOODS' # changes blue banner
admin.site.index_title = 'ADMIN DASHBOARD' # changes title under blue banner
admin.site.site_title = 'Hap-Pea Foods Admin' # changes browser tab title

urlpatterns = [
    path('admin/', admin.site.urls),
    url('about/', views.about, name="about"),
    url('donate/', include('donations.urls')),
    url('survey/', include('survey.urls')),
    url('find_help/', views.find_help, name="find_help"),
    url('partners/', views.partners, name="partners"),
    url('accounts/', include('accounts.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url('stories/', include('stories.urls')),
    url('events/', include('events.urls')),
    url('volunteer/', views.volunteer, name="volunteer"),
    url('portal/', views.portal, name="portal"),
    url('contact/', views.contact, name="contact"),
    url('createevent/', views.createevent, name="createevent"),
    url('moneydonations/', views.moneydonations, name="moneydonations"),
    url('organizations/', views.organizations, name="organizations"),
    url('mycalendar/', views.mycalendar, name="mycalendar"),
    url('non_disc_stmt/', views.non_disc_stmt, name="non_disc_stmt"),
    url('privacy/', views.privacy, name="privacy"),
    url('facts/', views.facts, name="facts"),
    url('terms_cond/', views.terms_cond, name="terms_cond"),
    #path('', include('qr_code.urls', namespace='qr_code')),
    url('', views.homepage, name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stories/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'stories'

urlpatterns = [

    url(r'^$', views.stories_list, name="stories"),
    url('create_story/', views.story_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', views.story_detail, name="detail"),
]

stories/models.py
from django.db import models

# Create your models here.
class Story(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    #thumb = models.ImageField(upload_to='images/', blank=True)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + "..."

stories/forms.py
from django import forms
from . import models

class CreateStory(forms.ModelForm):
    class Meta:
        model = models.Story
        fields= ['title','slug', 'body']

stories/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .models import Story
from . import forms

# Create your views here.
def stories_list(request):
    stories = Story.objects.all().order_by('date')
    return render(request, 'stories/stories_list.html', {'stories':stories})

def story_detail(request, slug):
    #return HttpResponse(slug)
    story = Story.objects.get(slug=slug)
    return render(request, 'stories/story_detail.html', {'story':story})

@login_required(login_url="/accounts/login/")
def story_create(request):
    if request.method == 'POST':
        #form = forms.CreateStory(request.POST, request.FILES) #use this if you have thumbnails on form
        form = forms.CreateStory(request.POST) #Use if no images on form
        if form.is_valid():
            form.save()
            return redirect("stories:stories")
    else:
        form = forms.CreateStory()
    return render(request, 'stories/story_create.html', {'form':form})

stories/templates/stories/stories_list.html
{% extends 'base_layout.html' %}
{% block title %} Hap-Pea Foods | User Stories {% endblock %}

{% block content %}
  <h1>User Stories</h1>

  <div class="createstory">
    <form class="create" action="{% url 'stories:create' %}" method="post">
      {% csrf_token %}
      <button type="submit" name="addstory">Create A Story</button>
    </form>
  </div>

  <div class="stories">
    {% for story in stories %}
      <div class= "story">
        <h2><a href="{% url 'stories:detail' slug=story.slug %}">{{story.title}}</a></h2>
        <p>{{story.snippet}}</p>
        <p> {{story.date}}</p>
      </div>
    {% endfor %}
  </div>



{% endblock %}

stories/templates/stories/story_create.html
{% extends 'base_layout.html' %}
{% block title %} Hap-Pea Foods | Create A Story {% endblock %}
{% block content %}

<div class="create-story">
  <h2>Create a Story!</h2>
  <form class="site-form" action="{% url 'stories:create' %}" method="post">  <!--use: enctype="multipart/form-data"   if you upload images -->
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Create Story">
  </form>
</div>

{% endblock %}

stories/templates/stories/story_detail.html
{% extends 'base_layout.html' %}
{% block title %} Hap-Pea Foods | Story {% endblock %}
{% block content %}
<div class="story-detail">
  <div class= "story">
    <h1>{{story.title}}</h1>
    <!-- <img src="{{ story.thumb.url}}"> -->
      <p>{{story.date}}</p>
      <p>{{story.body}}</p>
    </div>
</div>
{% endblock %}